package com.leetcode.hashtable;

import java.util.HashSet;
import java.util.Set;

/**
 * Created by Michael on 2016/8/29.
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 *
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 *
 * Function Signature:
 * public char findDifference(String a, String b) {...}
 */
public class E389_Find_String_Difference {
    public static void main(String[] args) {
        System.out.println(findDifference2("abcde", "abcdef"));
    }

    // 加减解法，可以避免因为不断求和而出现的overflow
    // time - o(n)
    // space - o(1)
    static char findDifference2(String a, String b) {
        char result = b.charAt(b.length() - 1);
        for (int i = 0; i < a.length(); i++) {
            result += b.charAt(i);
            result -= a.charAt(i);
        }
        return result;
    }
    // 比特翻转解法
    // time - o(n)
    // space - o(1)
    // 需要注意将0赋给char类型变量时，其值为'\u0000'，对应的二进制值就是全0，所以根本不需要最后异或掉初始值。
    // 如果将'0'赋给char类型变量时，其ASCII值才是48，即110000
    static char findDifference(String a, String b) {
        char result = '0';
        for (char x : a.toCharArray())
            result ^= x;
        for (char x : b.toCharArray())
            result ^= x;
        return result;
    }
}
